name: packaging

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Package VS code extension
        run: |
          npm install vsce --save-dev
          vsce package
      - name: Archive vsix file
        uses: actions/upload-artifact@v2
        with:
          name: darkturquiose-extension
          path: ./*.vsix
